INSERT INTO word (name) VALUES ('cat')
INSERT INTO word (name) VALUES ('mouse')
INSERT INTO word (name) VALUES ('cow')
INSERT INTO word (name) VALUES ('sheep')
INSERT INTO word (name) VALUES ('horse')
